scripts/vpnc-wrapper: tabs to 2 spaces (attic?)

diff --git a/scripts/vpnc-wrapper b/scripts/vpnc-wrapper
--- a/scripts/vpnc-wrapper
+++ b/scripts/vpnc-wrapper
@@ -5,8 +5,8 @@
 #
 
 whoami | grep -q ^root$ || {
-	echo "please run this as root (via sudo)"
-	exit 1
+  echo "please run this as root (via sudo)"
+  exit 1
 }
 
 # required programs
@@ -18,10 +18,10 @@ vpnif="tun0"
 
 # check for required programs
 for reqprog in ${reqprogs} ; do
-	which "${reqprog}" >/dev/null 2>&1 || {
-		echo "${i}: required program not found"
-		exit 1
-	}
+  which "${reqprog}" >/dev/null 2>&1 || {
+    echo "${i}: required program not found"
+    exit 1
+  }
 done
 
 # make our runtime directory
@@ -32,18 +32,18 @@ test -e /var/run/vpnc || mkdir -p /var/run/vpnc
 # from shill_main.cc, this should be a comma-separated list
 tr \\0 \\n < /proc/$(pgrep shill)/environ | \
   grep -q "^BLOCKED_DEVICES=${vpnif}$" || {
-	echo "adding ${vpnif} to shill BLOCKED_DEVICES"
-	echo "restarting shill"
-	stop shill
-	sleep ${sleeptime}
-	start shill BLOCKED_DEVICES="${vpnif}"
+  echo "adding ${vpnif} to shill BLOCKED_DEVICES"
+  echo "restarting shill"
+  stop shill
+  sleep ${sleeptime}
+  start shill BLOCKED_DEVICES="${vpnif}"
 }
 sleep ${sleeptime}
 
 # check for and create our vpn device
 ifconfig -a | grep -q "^${vpnif}" || {
-	echo "adding tunnel device ${vpnif} with openvpn"
-	openvpn --mktun --dev "${vpnif}"
+  echo "adding tunnel device ${vpnif} with openvpn"
+  openvpn --mktun --dev "${vpnif}"
 }
 sleep ${sleeptime}
 
